### ISSUE TITLE
It doesn't work on Chrome

### ISSUE THREAD

**Issue by gscalzo** [quirkey/the_json_store#1]
Very nice tutorial, but it seems not working on Chrome.
I tried Safari and Firefox and all went well, but on Chrome 
$.ajax({
    url: 'data/items.js', 
    dataType: 'json',
    success: function(items) {
      $.each(items, function(i, item) {
        context.log(item.title, '-', item.artist);
      });
    }
  });
});               

return a parserror

**Comment by quirkey** [comment]
Hey gscalzo 

For some reason I didnt get a notification about this . . . 

Anyway, the example wont work on chrome without loading it up in a webserver (local apache, sinatra, etc) because Chrome no longer supports AJAX calls over the file:// protocol.
