### ISSUE TITLE
All items loading but only last item rendering.

### ISSUE THREAD

**Issue by lgomez** [quirkey/the_json_store#2]
Hi! Just stumbled onto your project. It's awesome! You've done some great work and I'm considering using this in production already.

The problem I'm having is that I keep getting my first three items replaced by http://github.com/lgomez/sammy-test/blob/master/javascripts/app.js#L23-25. The items are all being loaded and `$.each(context.items, function(i, item) {` is running four times. But the result I get is a single item in #main (which in my case is #content). This is the entire content of the items section as shown by firebug: http://github.com/lgomez/sammy-test/blob/master/result.html.

I've looked through the code, tried your version, copied your app.js file from this project exactly as it is, etc... but still get the same problem. I can't see it. Thoughts?

Thank you!

**Comment by lgomez** [comment]
I always make the same mistake and overexplain.. basically the loop is replacing the contents of main instead of appending even though it clearly says `context.$element().append(rendered);`. Thanks again.

**Comment by quirkey** [comment]
Hey lgomez

I think you might have some additional issues as well because the API for template rendering has changed in Sammy 0.6 (which you're using in your test project) and I still need to update the tutorial JSON store code.

**Comment by lgomez** [comment]
I did make a change that solved it by changing the content of that $.each iterator to:

`context.render('templates/item.template', {id: i, item: item}).appendTo('#content');`

I don't know if that's right based on your changes but it worked. Thanks!

Do you need/want some help? I'm happy to chip in if you'd like. Always willing to help out on interesting projects.

Cheers,

Luis
