### ISSUE TITLE
sammy.template.js non-escaped output

### ISSUE THREAD

**Issue by andrewcrook** [quirkey/the_json_store#6]
I have created a few helpers that produce HTML, however,  all output from <%= %> seems to be escaped. Is there away to override this behaviour ?

if not, could this functionality be considered in future updates? I much rather have the option (a option as to maintain backward compatibility) to disable this feature so all output is raw and then create a helper to escape output when required on a per item bases. Perhaps such a helper could also be included?

**Comment by quirkey** [comment]
Yes, this is part of Sammy.Template already.
See: 
http://sammyjs.org/docs/api/master/all#Sammy.Template

You can use `<%! %>`
